# Actividad - Trabajando con DataFrames de Pandas.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: pandas_df_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter
* Deben trabajar con el datasets adjunto a la actividad

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

In [4]:
import pandas as pd
import sqlite3

#Aqui agrega la conexión a la base de datos

conn = sqlite3.connect('Salaries.sqlite')

#Crea el dataframe con los datos del datasets

df = pd.read_sql_query("SELECT * FROM salaries", conn)
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,None,567595.43,567595.43,2011,None,San Francisco,None
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,None,538909.28,538909.28,2011,None,San Francisco,None
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,None,335279.91,335279.91,2011,None,San Francisco,None
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,None,332343.61,332343.61,2011,None,San Francisco,None
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,None,326373.19,326373.19,2011,None,San Francisco,None

1. **Top 10 empleados con mayor salario total (incluyendo beneficios)**
Extrae e imprime un top 10 de expleados con mayor salario incluyendo los beneficios

In [9]:
#todo

# Obtener el top 10 empleados con mayor salario total
top_10_empleados = df.sort_values(by='TotalPayBenefits', ascending=False).head(10)

# mostramos el top 10
top_10_empleados

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,None,567595.43,567595.43,2011,None,San Francisco,None
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,None,538909.28,538909.28,2011,None,San Francisco,None
110531,110532,David Shinn,Deputy Chief 3,129150.01,0.0,342802.63,38780.04,471952.64,510732.68,2014,None,San Francisco,PT
110532,110533,Amy P Hart,Asst Med Examiner,318835.49,10712.95,60563.54,89540.23,390111.98,479652.21,2014,None,San Francisco,FT
110533,110534,William J Coaker Jr.,Chief Investment Officer,257340.0,0.0,82313.7,96570.66,339653.70,436224.36,2014,None,San Francisco,PT
72925,72926,Gregory P Suhr,Chief of Police,319275.01,0.0,20007.06,86533.21,339282.07,425815.28,2013,None,San Francisco,None
72926,72927,Joanne M Hayes-White,"Chief, Fire Department",313686.01,0.0,23236.0,85431.39,336922.01,422353.40,2013,None,San Francisco,None
110534,110535,Gregory P Suhr,Chief of Police,307450.04,0.0,19266.72,91302.46,326716.76,418019.22,2014,None,San Francisco,FT
110535,110536,Joanne M Hayes-White,"Chief, Fire Department",302068.0,0.0,24165.44,91201.66,326233.44,417435.10,2014,None,San Francisco,FT
110536,110537,Ellen G Moffatt,Asst Med Examiner,270222.04,6009.22,67956.2,71580.48,344187.46,415767.94,2014,None,San Francisco,FT

2. **Filtrar empleados con más de 50,000 en horas extra, la columna a tratar es: (OvertimePay)**

In [ ]:
#todo

# cambia textos no numéricos por NaN
df['OvertimePay'] = pd.to_numeric(df['OvertimePay'], errors='coerce')

# filtrar los empleados con mas de 50k en pagos extra
df_filtrado = df[df['OvertimePay'] > 50000].sort_values(by='OvertimePay', ascending=False)

# muestro los primeros 10
df_filtrado.head(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,None,538909.28,538909.28,2011,None,San Francisco,None
36159,36160,Gary Altenberg,"Lieutenant, Fire Suppression",128808.87,220909.48,13126.31,44430.12,362844.66,407274.78,2012,None,San Francisco,None
72964,72965,Whitney P Yee,Deputy Sheriff,95123.0,196689.18,16622.66,36125.49,308434.84,344560.33,2013,None,San Francisco,None
36163,36164,Frederick Binkley,EMT/Paramedic/Firefighter,126863.19,192424.49,17917.18,44438.25,337204.86,381643.11,2012,None,San Francisco,None
110574,110575,Antonio B Santiago,Deputy Sheriff,94191.04,173547.73,19740.81,38238.57,287479.58,325718.15,2014,None,San Francisco,FT
110577,110578,Barry J Bloom,Deputy Sheriff,94191.13,173178.23,17960.11,38171.49,285329.47,323500.96,2014,None,San Francisco,FT
110583,110584,Whitney P Yee,Deputy Sheriff,94191.0,169659.92,16813.46,38311.07,280664.38,318975.45,2014,None,San Francisco,FT
72943,72944,Gary L Altenberg,"Lieutenant, Fire Suppression",135903.02,163477.81,20994.96,46030.76,320375.79,366406.55,2013,None,San Francisco,None
36199,36200,Scott Scholzen,Firefighter,109783.86,160418.47,19873.8,41230.89,290076.13,331307.02,2012,None,San Francisco,None
73021,73022,Barry J Bloom,Deputy Sheriff,95123.08,156077.49,17018.22,35837.91,268218.79,304056.70,2013,None,San Francisco,None

3. **Contar cuántos empleados únicos hay por año**

In [21]:
#todo
# agrupa por año y luego contamos el registro unico en empleados de cada año
df.groupby('Year')['EmployeeName'].nunique()

Year
2011    33878
2012    34349
2013    36150
2014    36684
Name: EmployeeName, dtype: int64

4. **Ver cuántos cargos únicos (JobTitle) existen y los 5 más comunes**

In [23]:
#todo

# contar cuantos cargos unicos hay
num_cargos_unicos = df['JobTitle'].nunique()

#trae los mas comunes y pone los primeros 5
top5_cargos = df['JobTitle'].value_counts().head(5)

print("cargos unicos:", num_cargos_unicos)
print("top 5 cargos mas comunes:\n", top5_cargos)

cargos unicos: 2159
top 5 cargos mas comunes:
 JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

5. **Mostrar el salario total (TotalPay) promedio por año**

In [25]:
#todo

# calculamos el salario total promedio por cada año
salario_promedio_por_año = df.groupby('Year')['TotalPay'].mean().round(2)

# mostramos los resultados
print(salario_promedio_por_año)

Year
2011    71744.10
2012    74113.26
2013    77611.44
2014    75463.92
Name: TotalPay, dtype: float64

6. **Exporta todos los datos a un CSV y muestra los ultimos 10 valores**

In [26]:
#todo

df.to_csv('todos_datos.csv', index=False)

# ultimos 10 registros
df.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.00,0.0,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.0,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148646,148647,Not provided,Not provided,Not Provided,NaN,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.0,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148648,148649,Leon Walker,Custodian,0.00,0.0,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148649,148650,Roy I Tillery,Custodian,0.00,0.0,0.00,0.00,0.00,0.00,2014,None,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,NaN,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148651,148652,Not provided,Not provided,Not Provided,NaN,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148652,148653,Not provided,Not provided,Not Provided,NaN,Not Provided,Not Provided,0.00,0.00,2014,None,San Francisco,None
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.0,-618.13,0.00,-618.13,-618.13,2014,None,San Francisco,PT